### ISSUE TITLE
Message not send in the starboard

### ISSUE THREAD

**Issue by HideakiAtsuyo** [Yousef101/iStar#2]
All is in the title :)

**Comment by HideakiAtsuyo** [comment]
And if the reaction is put on another server containing the bot, it causes a crash!

**Comment by Yousef101** [comment]
1:: Make sure you specify the threshold in settings.json to a number (the amount of reactions needed to post in a channel)

2:: this version of iStar can only be used in one server. 

For further assistance https://discord.gg/TWy6pSZ
